-- Big Two Vakantiestand – Supabase-installatie / update
-- Voer dit hele bestand uit in: Supabase > SQL Editor > New query.
-- Het script kan opnieuw worden uitgevoerd om een bestaande installatie bij te werken.
-- Publieke bezoekers hebben geen groepscode nodig. Alleen beheeracties vereisen de beheerderscode.
-- Kaartenaantallen worden aangepast aan het aantal spelers; strafpunten zijn maximaal 39.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.big2_groups (
  id uuid primary key default extensions.gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,39}$'),
  name text not null check (char_length(name) between 2 and 80),
  admin_pin_hash text not null,
  created_at timestamptz not null default now()
);

-- Verwijder de niet meer gebruikte groepscode uit bestaande installaties.
alter table public.big2_groups drop column if exists pin_hash;

create table if not exists public.big2_players (
  id uuid primary key default extensions.gen_random_uuid(),
  group_id uuid not null references public.big2_groups(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 40),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists big2_players_group_name_unique on public.big2_players (group_id, lower(name));

create table if not exists public.big2_games (
  id uuid primary key default extensions.gen_random_uuid(),
  group_id uuid not null references public.big2_groups(id) on delete cascade,
  played_at timestamptz not null default now(),
  entered_by uuid not null references public.big2_players(id),
  winner uuid not null references public.big2_players(id),
  entries jsonb not null check (jsonb_typeof(entries) = 'array'),
  note text check (char_length(note) <= 160),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz
);
alter table public.big2_games add column if not exists updated_at timestamptz;
create index if not exists big2_games_group_played_at_idx on public.big2_games(group_id, played_at desc) where deleted_at is null;

create table if not exists public.big2_audit_logs (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.big2_groups(id) on delete cascade,
  actor_player_id uuid references public.big2_players(id) on delete set null,
  actor_name text not null check (char_length(actor_name) between 1 and 80),
  action text not null check (action in (
    'site_access', 'game_added', 'game_updated', 'game_deleted', 'player_added', 'player_status_changed'
  )),
  entity_type text,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists big2_audit_logs_group_created_idx on public.big2_audit_logs(group_id, created_at desc);

alter table public.big2_groups enable row level security;
alter table public.big2_players enable row level security;
alter table public.big2_games enable row level security;
alter table public.big2_audit_logs enable row level security;
revoke all on public.big2_groups, public.big2_players, public.big2_games, public.big2_audit_logs from anon, authenticated;

create or replace function public.big2_penalty(p_cards integer)
returns integer language sql immutable strict set search_path = public as $$
  select case when p_cards >= 13 then 39 when p_cards >= 10 then p_cards * 2 else p_cards end;
$$;

create or replace function public.big2_public_group_id(p_slug text)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_group_id uuid;
begin
  select id into v_group_id from public.big2_groups where slug = lower(trim(p_slug));
  if not found then raise exception 'Groep niet gevonden'; end if;
  return v_group_id;
end;
$$;

create or replace function public.big2_admin_group_id(p_slug text, p_admin_pin text)
returns uuid language plpgsql security definer set search_path = public, extensions as $$
declare v_group public.big2_groups%rowtype;
begin
  select * into v_group from public.big2_groups where slug = lower(trim(p_slug));
  if not found then raise exception 'Groep niet gevonden'; end if;
  if p_admin_pin is null or trim(p_admin_pin) = '' then raise exception 'Beheerderscode ontbreekt'; end if;
  if extensions.crypt(p_admin_pin, v_group.admin_pin_hash) <> v_group.admin_pin_hash then
    raise exception 'Beheerderscode onjuist';
  end if;
  return v_group.id;
end;
$$;

create or replace function public.big2_actor_name(p_group_id uuid, p_actor_id uuid, p_actor_name text)
returns text language plpgsql security definer set search_path = public as $$
declare v_name text;
begin
  if p_actor_id is not null then
    select name into v_name from public.big2_players where id = p_actor_id and group_id = p_group_id;
    if not found then raise exception 'Gebruiker niet gevonden'; end if;
    return v_name;
  end if;
  v_name := nullif(trim(coalesce(p_actor_name, '')), '');
  return left(coalesce(v_name, 'Beheerder'), 80);
end;
$$;

create or replace function public.big2_write_log(
  p_group_id uuid, p_actor_id uuid, p_actor_name text, p_action text,
  p_entity_type text default null, p_entity_id uuid default null, p_details jsonb default '{}'::jsonb
)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.big2_audit_logs(group_id, actor_player_id, actor_name, action, entity_type, entity_id, details)
  values (
    p_group_id, p_actor_id, public.big2_actor_name(p_group_id, p_actor_id, p_actor_name),
    p_action, p_entity_type, p_entity_id, coalesce(p_details, '{}'::jsonb)
  );
end;
$$;

create or replace function public.big2_normalize_entries(
  p_group_id uuid, p_winner uuid, p_entries jsonb, p_require_active boolean default true
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_count integer;
  v_unique integer;
  v_invalid integer;
  v_winner_rows integer;
  v_max_cards integer;
  v_normalized jsonb;
begin
  if jsonb_typeof(p_entries) <> 'array' then raise exception 'Ongeldige spelerslijst'; end if;

  select count(*), count(distinct e.player_id),
         count(*) filter (where e.player_id = p_winner and e.cards = 0)
  into v_count, v_unique, v_winner_rows
  from jsonb_to_recordset(p_entries) as e(player_id uuid, cards integer);

  if v_count < 2 or v_count > 8 or v_count <> v_unique then raise exception 'Selecteer 2 tot 8 unieke spelers'; end if;
  v_max_cards := ceil(52.0 / v_count);

  -- Null-waarden worden hier expliciet geweigerd. Een vergelijking met null levert null op
  -- in plaats van waar of onwaar, waardoor een ontbrekend kaartenaantal anders ongemerkt
  -- alle onderstaande controles passeert en als nul strafpunten in de stand terechtkomt.
  select count(*) filter (where e.player_id is null or e.cards is null or e.cards < 0 or e.cards > v_max_cards)
  into v_invalid
  from jsonb_to_recordset(p_entries) as e(player_id uuid, cards integer);

  if v_invalid > 0 or v_winner_rows <> 1 then raise exception 'Ongeldige kaartenaantallen of winnaar'; end if;
  if exists (
    select 1 from jsonb_to_recordset(p_entries) as e(player_id uuid, cards integer)
    where e.player_id <> p_winner and (e.cards is null or e.cards < 1 or e.cards > v_max_cards)
  ) then raise exception 'Verliezers moeten 1 tot % kaarten hebben', v_max_cards; end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_entries) as e(player_id uuid, cards integer)
    left join public.big2_players p on p.id = e.player_id and p.group_id = p_group_id
    where p.id is null or (p_require_active and not p.active)
  ) then raise exception 'Een geselecteerde speler is niet beschikbaar'; end if;

  select jsonb_agg(
    jsonb_build_object('player_id', e.player_id, 'cards', e.cards, 'penalty', public.big2_penalty(e.cards))
    order by e.cards, e.player_id
  ) into v_normalized
  from jsonb_to_recordset(p_entries) as e(player_id uuid, cards integer);

  return v_normalized;
end;
$$;

create or replace function public.big2_state(p_group_id uuid)
returns jsonb language sql security definer set search_path = public as $$
  select jsonb_build_object(
    'group', (
      select jsonb_build_object('id', g.id, 'slug', g.slug, 'name', g.name)
      from public.big2_groups g where g.id = p_group_id
    ),
    'players', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'active', p.active) order by p.active desc, lower(p.name))
      from public.big2_players p where p.group_id = p_group_id
    ), '[]'::jsonb),
    'games', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', x.id, 'played_at', x.played_at, 'created_at', x.created_at, 'updated_at', x.updated_at,
        'entered_by', x.entered_by, 'winner', x.winner, 'entries', x.entries, 'note', x.note
      ) order by x.played_at desc, x.created_at desc)
      from public.big2_games x where x.group_id = p_group_id and x.deleted_at is null
    ), '[]'::jsonb),
    'logs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', l.id, 'actor_player_id', l.actor_player_id, 'actor_name', l.actor_name,
        'action', l.action, 'entity_type', l.entity_type, 'entity_id', l.entity_id,
        'details', l.details, 'created_at', l.created_at
      ) order by l.created_at desc, l.id desc)
      from (
        select * from public.big2_audit_logs
        where group_id = p_group_id
        order by created_at desc, id desc
        limit 500
      ) l
    ), '[]'::jsonb)
  );
$$;

-- Verwijder openbare functievarianten uit versies met een groepscode.
drop function if exists public.big2_bootstrap(text,text);
drop function if exists public.big2_log_access(text,text,uuid,text);
drop function if exists public.big2_add_game(text,text,uuid,text,uuid,uuid,jsonb,text);
drop function if exists public.big2_add_game(text,text,uuid,uuid,jsonb,text);

-- Verwijder en vervang beheerfuncties, zodat ze niet meer afhankelijk zijn van de oude groepscodefunctie.
drop function if exists public.big2_admin_update_game(text,text,uuid,text,uuid,uuid,jsonb,text);
drop function if exists public.big2_admin_add_player(text,text,uuid,text,text);
drop function if exists public.big2_admin_add_player(text,text,text);
drop function if exists public.big2_admin_add_players(text,text,uuid,text,jsonb);
drop function if exists public.big2_admin_set_player_active(text,text,uuid,text,uuid,boolean);
drop function if exists public.big2_admin_set_player_active(text,text,uuid,boolean);
drop function if exists public.big2_admin_delete_game(text,text,uuid,text,uuid);
drop function if exists public.big2_admin_delete_game(text,text,uuid);
drop function if exists public.big2_group_id(text,text,boolean);

create or replace function public.big2_bootstrap(p_slug text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_group_id uuid;
begin
  v_group_id := public.big2_public_group_id(p_slug);
  return public.big2_state(v_group_id);
end;
$$;

create or replace function public.big2_log_access(
  p_slug text, p_actor_id uuid, p_actor_name text
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_group_id uuid;
begin
  v_group_id := public.big2_public_group_id(p_slug);

  -- Hoogstens één bezoekregel per gebruiker per tien minuten. Deze functie is openbaar,
  -- dus zonder deze controle kan het logboek onbeperkt worden volgeschreven.
  if not exists (
    select 1 from public.big2_audit_logs
    where group_id = v_group_id
      and action = 'site_access'
      and actor_player_id is not distinct from p_actor_id
      and created_at > now() - interval '10 minutes'
  ) then
    perform public.big2_write_log(v_group_id, p_actor_id, p_actor_name, 'site_access', 'site', null, '{}'::jsonb);
  end if;

  return public.big2_state(v_group_id);
end;
$$;

create or replace function public.big2_add_game(
  p_slug text, p_actor_id uuid, p_actor_name text,
  p_entered_by uuid, p_winner uuid, p_entries jsonb, p_note text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_group_id uuid;
  v_normalized jsonb;
  v_game public.big2_games%rowtype;
begin
  v_group_id := public.big2_public_group_id(p_slug);

  -- Iedereen met de link mag potjes toevoegen, dus staat hier een eenvoudige rem tegen
  -- geautomatiseerd volschrijven van de database. Normaal gebruik haalt deze grens nooit.
  if (
    select count(*) from public.big2_games
    where group_id = v_group_id and created_at > now() - interval '1 minute'
  ) >= 20 then
    raise exception 'Er zijn zojuist veel potjes achter elkaar ingevoerd. Probeer het over een minuut opnieuw.';
  end if;

  v_normalized := public.big2_normalize_entries(v_group_id, p_winner, p_entries, true);

  if not exists (
    select 1 from public.big2_players where id = p_entered_by and group_id = v_group_id and active
  ) then raise exception 'Ongeldige invoerder'; end if;

  insert into public.big2_games(group_id, entered_by, winner, entries, note)
  values (v_group_id, p_entered_by, p_winner, v_normalized, nullif(trim(p_note), ''))
  returning * into v_game;

  perform public.big2_write_log(
    v_group_id, p_actor_id, p_actor_name, 'game_added', 'game', v_game.id,
    jsonb_build_object('game', to_jsonb(v_game) - 'group_id' - 'deleted_at')
  );
  return public.big2_state(v_group_id);
end;
$$;

create or replace function public.big2_admin_update_game(
  p_slug text, p_admin_pin text, p_actor_id uuid, p_actor_name text,
  p_game_id uuid, p_winner uuid, p_entries jsonb, p_note text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_group_id uuid;
  v_normalized jsonb;
  v_before public.big2_games%rowtype;
  v_after public.big2_games%rowtype;
begin
  v_group_id := public.big2_admin_group_id(p_slug, p_admin_pin);
  select * into v_before from public.big2_games
  where id = p_game_id and group_id = v_group_id and deleted_at is null;
  if not found then raise exception 'Potje niet gevonden'; end if;

  v_normalized := public.big2_normalize_entries(v_group_id, p_winner, p_entries, false);

  -- Een correctie wijzigt alleen winnaar, kaarten en opmerking. De website biedt geen knop
  -- om deelnemers te wisselen, dus dat wordt hier ook op de server geweigerd.
  if exists (
    select (v->>'player_id')::uuid from jsonb_array_elements(v_normalized) v
    except
    select (v->>'player_id')::uuid from jsonb_array_elements(v_before.entries) v
  ) or exists (
    select (v->>'player_id')::uuid from jsonb_array_elements(v_before.entries) v
    except
    select (v->>'player_id')::uuid from jsonb_array_elements(v_normalized) v
  ) then
    raise exception 'De deelnemers van een potje kunnen niet worden gewijzigd. Verwijder het potje en voer het opnieuw in.';
  end if;

  update public.big2_games
  set winner = p_winner, entries = v_normalized, note = nullif(trim(p_note), ''), updated_at = now()
  where id = p_game_id
  returning * into v_after;

  perform public.big2_write_log(
    v_group_id, p_actor_id, p_actor_name, 'game_updated', 'game', p_game_id,
    jsonb_build_object(
      'before', to_jsonb(v_before) - 'group_id' - 'deleted_at',
      'after', to_jsonb(v_after) - 'group_id' - 'deleted_at'
    )
  );
  return public.big2_state(v_group_id);
end;
$$;

create or replace function public.big2_admin_add_players(
  p_slug text, p_admin_pin text, p_actor_id uuid, p_actor_name text, p_names jsonb
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_group_id uuid;
  v_name text;
  v_player public.big2_players%rowtype;
  v_count integer;
begin
  v_group_id := public.big2_admin_group_id(p_slug, p_admin_pin);
  if jsonb_typeof(p_names) <> 'array' then raise exception 'Ongeldige namenlijst'; end if;

  select count(*) into v_count
  from (
    select distinct trim(value) as name
    from jsonb_array_elements_text(p_names)
    where char_length(trim(value)) between 2 and 40
  ) names;

  if v_count < 1 or v_count > 30 then raise exception 'Voer 1 tot 30 geldige namen in'; end if;

  for v_name in
    select distinct trim(value)
    from jsonb_array_elements_text(p_names)
    where char_length(trim(value)) between 2 and 40
    order by 1
  loop
    insert into public.big2_players(group_id, name)
    values (v_group_id, v_name)
    returning * into v_player;

    perform public.big2_write_log(
      v_group_id, p_actor_id, p_actor_name, 'player_added', 'player', v_player.id,
      jsonb_build_object('name', v_player.name)
    );
  end loop;

  return public.big2_state(v_group_id);
exception when unique_violation then raise exception 'Minstens één speler bestaat al';
end;
$$;

create or replace function public.big2_admin_set_player_active(
  p_slug text, p_admin_pin text, p_actor_id uuid, p_actor_name text,
  p_player_id uuid, p_active boolean
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_group_id uuid;
  v_player public.big2_players%rowtype;
  v_previous_active boolean;
begin
  v_group_id := public.big2_admin_group_id(p_slug, p_admin_pin);
  select * into v_player from public.big2_players where id = p_player_id and group_id = v_group_id;
  if not found then raise exception 'Speler niet gevonden'; end if;
  v_previous_active := v_player.active;
  update public.big2_players set active = p_active where id = p_player_id;
  perform public.big2_write_log(
    v_group_id, p_actor_id, p_actor_name, 'player_status_changed', 'player', p_player_id,
    jsonb_build_object('name', v_player.name, 'previous_active', v_previous_active, 'active', p_active)
  );
  return public.big2_state(v_group_id);
end;
$$;

create or replace function public.big2_admin_delete_game(
  p_slug text, p_admin_pin text, p_actor_id uuid, p_actor_name text, p_game_id uuid
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_group_id uuid;
  v_game public.big2_games%rowtype;
begin
  v_group_id := public.big2_admin_group_id(p_slug, p_admin_pin);
  select * into v_game from public.big2_games
  where id = p_game_id and group_id = v_group_id and deleted_at is null;
  if not found then raise exception 'Potje niet gevonden'; end if;

  update public.big2_games set deleted_at = now() where id = p_game_id;
  perform public.big2_write_log(
    v_group_id, p_actor_id, p_actor_name, 'game_deleted', 'game', p_game_id,
    jsonb_build_object('game', to_jsonb(v_game) - 'group_id' - 'deleted_at')
  );
  return public.big2_state(v_group_id);
end;
$$;

revoke all on function public.big2_penalty(integer) from public;
revoke all on function public.big2_public_group_id(text) from public;
revoke all on function public.big2_admin_group_id(text,text) from public;
revoke all on function public.big2_actor_name(uuid,uuid,text) from public;
revoke all on function public.big2_write_log(uuid,uuid,text,text,text,uuid,jsonb) from public;
revoke all on function public.big2_normalize_entries(uuid,uuid,jsonb,boolean) from public;
revoke all on function public.big2_state(uuid) from public;
revoke all on function public.big2_bootstrap(text) from public;
revoke all on function public.big2_log_access(text,uuid,text) from public;
revoke all on function public.big2_add_game(text,uuid,text,uuid,uuid,jsonb,text) from public;
revoke all on function public.big2_admin_update_game(text,text,uuid,text,uuid,uuid,jsonb,text) from public;
revoke all on function public.big2_admin_add_players(text,text,uuid,text,jsonb) from public;
revoke all on function public.big2_admin_set_player_active(text,text,uuid,text,uuid,boolean) from public;
revoke all on function public.big2_admin_delete_game(text,text,uuid,text,uuid) from public;

grant execute on function public.big2_bootstrap(text) to anon, authenticated;
grant execute on function public.big2_log_access(text,uuid,text) to anon, authenticated;
grant execute on function public.big2_add_game(text,uuid,text,uuid,uuid,jsonb,text) to anon, authenticated;
grant execute on function public.big2_admin_update_game(text,text,uuid,text,uuid,uuid,jsonb,text) to anon, authenticated;
grant execute on function public.big2_admin_add_players(text,text,uuid,text,jsonb) to anon, authenticated;
grant execute on function public.big2_admin_set_player_active(text,text,uuid,text,uuid,boolean) to anon, authenticated;
grant execute on function public.big2_admin_delete_game(text,text,uuid,text,uuid) to anon, authenticated;

-- Maak één groep aan. Verander naam, slug en beheerderscode vóór de eerste uitvoering.
-- Bij een bestaande groep worden deze waarden niet overschreven.
--
-- BELANGRIJK: vul hieronder een eigen, lange beheerderscode in en zet die nooit in Git.
-- Een pincode van vier cijfers is niet voldoende: er is geen limiet op het aantal
-- pogingen, dus alle tienduizend mogelijkheden zijn in korte tijd te proberen.
insert into public.big2_groups(slug, name, admin_pin_hash)
values (
  'big2-vakantie-2026',
  'Big Two Vakantiestand 2026',
  extensions.crypt('VERVANG-DEZE-CODE', extensions.gen_salt('bf', 12))
)
on conflict (slug) do nothing;

-- Een bestaande beheerderscode wijzigen. Voer dit ook uit wanneer de code ooit in Git
-- heeft gestaan; het bovenstaande insert laat een bestaande groep bewust ongemoeid.
-- update public.big2_groups
-- set admin_pin_hash = extensions.crypt('NIEUWE-LANGE-CODE', extensions.gen_salt('bf', 12))
-- where slug = 'big2-vakantie-2026';
